### ISSUE TITLE
Throws error message when no food in inv

### ISSUE THREAD

**Issue by SinanAkkoyun** [LINKdiscordd/mineflayer-auto-eat#6]
```
Error: No food found.
    at eat (/mnt/c/Users/Sinan/node_modules/mineflayer-auto-eat/index.js:42:29)
    at EventEmitter.<anonymous> (/mnt/c/Users/Sinan/node_modules/mineflayer-auto-eat/index.js:110:17)
    at EventEmitter.emit (events.js:327:22)
    at Client.<anonymous> (/mnt/c/Users/Sinan/node_modules/mineflayer/lib/plugins/health.js:21:9)
    at Client.emit (events.js:327:22)
    at FullPacketParser.<anonymous> (/mnt/c/Users/Sinan/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/mnt/c/Users/Sinan/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/mnt/c/Users/Sinan/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/mnt/c/Users/Sinan/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:241:10)
```

Please make it silent or tell me how I can, just a try catch?

**Comment by Nachtschatten** [comment]
Agree, came here to raise the same issue. I didn't call `bot.autoEat.eat()` manually, I just let auto-eat do its thing. Since there was no food in the bot's inventory it continually threw stacktraces at me. That's not helpful at all.

**Comment by LINKdiscordd** [comment]
I just pushed a change and now it shouldn't spam errors anymore
